name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/*'  # Trigger on feature branch pushes for early planning

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Create main.tf (Simulated or Real)
      run: |
        cat <<EOF > main.tf
        resource "azurerm_virtual_desktop_host_pool" "example" {
          name                = "example"
          location            = "East US"
          resource_group_name = "example-resources"
          type                = "Pooled"
        }
        EOF

    - name: Initialize Terraform (Simulated or Real)
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Initializing Terraform... (Simulated)"
          echo "Terraform initialized (this is a simulation)."
        else
          terraform init
        fi

    - name: Format Check (Simulated or Real)
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Checking Terraform format... (Simulated)"
          echo "Terraform format is correct (this is a simulation)."
        else
          terraform fmt -check
        fi

    - name: Validate Terraform (Simulated or Real)
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Validating Terraform configuration... (Simulated)"
          echo "Terraform configuration is valid (this is a simulation)."
        else
          terraform validate
        fi

    - name: Terraform Plan (Simulated or Real)
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Running Terraform plan... (Simulated)"
          echo "Terraform plan created with the following changes (this is a simulation):"
          echo "- Created azurerm_virtual_desktop_host_pool.example"
          echo "Simulated plan saved to tfplan."
          echo "simulated_tfplan" > tfplan
        else
          terraform plan -out=tfplan
        fi

    - name: Apply Terraform Plan (Real only)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        terraform apply -auto-approve tfplan

