name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/*'  # Trigger on feature branch pushes for early planning

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Simulate main.tf creation
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Simulating main.tf creation"
          cat <<EOF > main.tf
resource "azurerm_virtual_desktop_host_pool" "example" {
  name                = "example"
  location            = "East US"
  resource_group_name = "example-resources"
  type                = "Pooled"
}
EOF
          echo "main.tf created."
        fi

    - name: Simulate Terraform Initialization
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Simulating Terraform initialization."
          echo "Terraform initialized (simulation only)."
        fi

    - name: Simulate Format Check
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Simulating Terraform format check."
          echo "Terraform format is correct (simulation only)."
        fi

    - name: Simulate Terraform Validation
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Simulating Terraform validation."
          echo "Terraform configuration is valid (simulation only)."
        fi

    - name: Simulate Terraform Plan
      run: |
        if [ "$SIMULATE_TERRAFORM" = "true" ]; then
          echo "Simulating Terraform plan."
          echo "Terraform plan created with the following changes (simulation only):"
          echo "- Created azurerm_virtual_desktop_host_pool.example"
          echo "Simulated plan saved to tfplan."
        fi
