name: Test Auto-Merge

on:
  pull_request:
    branches:
      - main
      - 'feature/*' # Trigger when PRs are made to main or feature branches
    types:
      - opened # Only run the workflow when a PR is opened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto-Merge PR
        if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attempting to merge pull request..."
          gh pr merge --auto --squash --subject "Auto-merged by Test Pipeline"

