name: Auto-Merge Pull Requests

on:
  pull_request:
    branches:
      - main # Only trigger for PRs targeting main
    types:
      - opened # Trigger when a PR is opened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }} # Dynamically fetch the branch name
          repository: ${{ github.event.pull_request.head.repo.full_name }} # Use the full repo path for PRs from forks

      - name: Auto-Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Attempting to merge pull request..."
          gh pr merge --auto --squash --subject "Auto-merged by CI pipeline"

